name: CI
on:
  push:
  pull_request:
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck bats shfmt
      - name: Lint
        run: make lint
      - name: Tests
        run: make test
